name: CI

on: [push, issue_comment]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: install dependencies
      run: |
        pip3 install -r requirements.txt
    - name: run python script
      env:
        GITHUB_LOGIN: zeilou
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: python3 main.py
    - name: config git info
      run: |
        git config --global user.email "lingyinziluo@163.com"
        git config --global user.name "zeilou"
    - name: commit change
      run: |
        git checkout master
        git add .
        git commit -m "Update from Github Action"
    - name: push change
      env:
        GITHUB_LOGIN: zeilou
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        git push https://$GITHUB_LOGIN:$GITHUB_TOKEN@github.com/cdn.git
    - name: done
      run: echo 'done'
