name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: install dependencies
      run: |
        pip3 install -r requirements.txt
    - name: run python script
      env:
        GITHUB_LOGIN: zeilou
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: python3 main.py
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        FOLDER: .
        BRANCH: gh-pages

